# Generated by Django 5.2.4 on 2026-02-09 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_initial'),
        ('Employee', '0003_employee_department_employee_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='Employee.businessprofile'),
        ),
    ]
