# Generated by Django 5.2.4 on 2026-01-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='Employee.businessprofile'),
        ),
    ]
